name: CFFNetx2
use_tb_logger: false
model: VideoSR_base
distortion: sr
scale: 2
gpu_ids: [0]
dist: true
time_pth: ~
use_time: true  # multi=slice interpolation
frame: 3
ssl: False   # self-supevise model

datasets:
  train:
    name: LITS
    mode: LITS
    interval_list: [1]
    random_reverse: true
    border_mode: false

    # x2 FSL
    dataroot_GT: /home/lpc/dataset/LITS_rec/ISO_LITS_seq3_train_GT.lmdb
    dataroot_LQ: /home/lpc/dataset/LITS_rec/ISO_LITS_seq3_train_GT.lmdb
    cache_keys: /home/lpc/dataset/LITS_rec/ISO_LITS_seq3_train_GT.lmdb/Vimeo7_train_keys.pkl
    # x4 FSL
    # dataroot_GT: /home/lpc/dataset/LITS_rec/ISO_LITS_seq5_train_GT.lmdb
    # dataroot_LQ: /home/lpc/dataset/LITS_rec/ISO_LITS_seq5_train_GT.lmdb
    # cache_keys: /home/lpc/dataset/LITS_rec/ISO_LITS_seq5_train_GT.lmdb/Vimeo7_train_keys.pkl
    # x6 FSL
    # dataroot_GT: /home/lpc/dataset/LITS_rec/ISO_LITS_seq7_inplane_train_GT.lmdb
    # dataroot_LQ: /home/lpc/dataset/LITS_rec/ISO_LITS_seq7_inplane_train_GT.lmdb
    # cache_keys: /home/lpc/dataset/LITS_rec/ISO_LITS_seq7_inplane_train_GT.lmdb/Vimeo7_train_keys.pkl
    
    N_frames: 3
    use_shuffle: true
    n_workers: 6
    batch_size: 16
    GT_size: 128  # crop size
    LQ_size: 128  # crop size
    LR_resolution: [1, 512, 512]
    HR_resolution: [1, 512, 512]
    use_flip: true
    use_rot: true
    color: RGB
    use_time: true
  
  val:
    name: LITS
    mode: Val_nii
    dataroot_GT: /home/lpc/dataset/LITS_rec/vessel_291
    dataroot_LQ: /home/lpc/dataset/LITS_rec/vessel_291
    N_frames: 3   # 数据采集帧数
    use_time: true

network_G:
  which_model_G: OURS_new
  nf: 64
  nframes: 3
  groups: 8
  front_RBs: 5
  mid_RBs: 0
  back_RBs: 10
  HR_in: false

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 100001
  warmup_iter: -1
  T_period: [100001]
  restarts: [100001]
  restart_weights: [1]
  eta_min: !!float 1e-5

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 1000

  manual_seed: 0


logger:
  print_freq: 10
  save_checkpoint_freq: !!float 1e3